apiVersion: v1
entries:
  karvdash:
  - apiVersion: v2
    created: "2021-06-04T14:17:26.36993158Z"
    description: Karvdash provides a complete software stack for performing data science
      on Kubernetes
    digest: 5e6dfd758d66b1b015568a9bd53621acb68c83729aafc970d0da7125996958b9
    kubeVersion: '>= 1.15.0'
    name: karvdash
    sources:
    - https://github.com/CARV-ICS-FORTH/karvdash
    type: application
    urls:
    - https://CARV-ICS-FORTH.github.io/karvdash/chart/karvdash-2.3.1.tgz
    version: 2.3.1
  - apiVersion: v2
    created: "2021-05-13T16:16:58.697636707Z"
    description: Karvdash provides a complete software stack for performing data science
      on Kubernetes
    digest: 616367217c2f1528d09aa89f1cbe25a15866d62524cef51eda6c3013d15f0fcf
    kubeVersion: '>= 1.15.0'
    name: karvdash
    sources:
    - https://github.com/CARV-ICS-FORTH/karvdash
    type: application
    urls:
    - https://CARV-ICS-FORTH.github.io/karvdash/chart/karvdash-2.3.0.tgz
    version: 2.3.0
  - apiVersion: v2
    created: "2021-05-07T09:56:46.696463892Z"
    description: Karvdash provides a complete software stack for performing data science
      on Kubernetes
    digest: 917de6860d287d29b9bf19d29d6192c86406616db58571d68226bf50486cb35f
    kubeVersion: '>= 1.15.0'
    name: karvdash
    sources:
    - https://github.com/CARV-ICS-FORTH/karvdash
    type: application
    urls:
    - https://CARV-ICS-FORTH.github.io/karvdash/chart/karvdash-2.2.0.tgz
    version: 2.2.0
  - apiVersion: v2
    created: "2021-04-14T10:59:53.350750644Z"
    description: Karvdash provides a complete software stack for performing data science
      on Kubernetes
    digest: d4ee54dd71c5363f4b4749f2ce99f1ff68f31837a577c9862662f4a043b66b7b
    kubeVersion: '>= 1.15.0'
    name: karvdash
    sources:
    - https://github.com/CARV-ICS-FORTH/karvdash
    type: application
    urls:
    - https://CARV-ICS-FORTH.github.io/karvdash/chart/karvdash-2.1.0.tgz
    version: 2.1.0
  - apiVersion: v2
    created: "2021-03-23T11:18:20.107824221Z"
    description: Karvdash provides a complete software stack for performing data science
      on Kubernetes
    digest: 7af593b35b77b7f4ee7166712d351d61b07903dd91c867128e58ae7a359f3597
    kubeVersion: '>= 1.15.0'
    name: karvdash
    sources:
    - https://github.com/CARV-ICS-FORTH/karvdash
    type: application
    urls:
    - https://CARV-ICS-FORTH.github.io/karvdash/chart/karvdash-2.0.0.tgz
    version: 2.0.0
generated: "2021-06-04T14:17:26.368931632Z"
