apiVersion: v1
entries:
  karvdash:
  - apiVersion: v2
    created: "2022-02-17T18:29:10.247512026Z"
    description: Karvdash provides a complete software stack for performing data science
      on Kubernetes
    digest: c444729fe7b0da1c874ca80114a0eb823b6069ef2328b8c2412ebfc796ccfef1
    kubeVersion: '>= 1.19.0'
    name: karvdash
    sources:
    - https://github.com/CARV-ICS-FORTH/karvdash
    type: application
    urls:
    - https://CARV-ICS-FORTH.github.io/karvdash/chart/karvdash-3.2.0.tgz
    version: 3.2.0
  - apiVersion: v2
    created: "2022-01-26T13:45:12.552528639Z"
    description: Karvdash provides a complete software stack for performing data science
      on Kubernetes
    digest: ebef82bcbce6fbc20db76fd017c60117d37c8367f3d2011db17d65d446458698
    kubeVersion: '>= 1.19.0'
    name: karvdash
    sources:
    - https://github.com/CARV-ICS-FORTH/karvdash
    type: application
    urls:
    - https://CARV-ICS-FORTH.github.io/karvdash/chart/karvdash-3.1.2.tgz
    version: 3.1.2
  - apiVersion: v2
    created: "2022-01-05T23:18:39.996923215Z"
    description: Karvdash provides a complete software stack for performing data science
      on Kubernetes
    digest: ee5771151c0e01ad6f9fbdcce143d2f768ad147454e9ccc91755fb4cc124c24a
    kubeVersion: '>= 1.19.0'
    name: karvdash
    sources:
    - https://github.com/CARV-ICS-FORTH/karvdash
    type: application
    urls:
    - https://CARV-ICS-FORTH.github.io/karvdash/chart/karvdash-3.1.1.tgz
    version: 3.1.1
  - apiVersion: v2
    created: "2021-12-14T16:06:52.662785464Z"
    description: Karvdash provides a complete software stack for performing data science
      on Kubernetes
    digest: dfe0879dd40d34d51d732cf7687d0d807a1eb07fc82afda222cff4517d1aa36c
    kubeVersion: '>= 1.19.0'
    name: karvdash
    sources:
    - https://github.com/CARV-ICS-FORTH/karvdash
    type: application
    urls:
    - https://CARV-ICS-FORTH.github.io/karvdash/chart/karvdash-3.1.0.tgz
    version: 3.1.0
  - apiVersion: v2
    created: "2021-11-30T12:03:26.139148116Z"
    description: Karvdash provides a complete software stack for performing data science
      on Kubernetes
    digest: 5a3c7d08dc34977ddea41b66399dc6b56fe154f1cb771673e5bdef281e2d1474
    kubeVersion: '>= 1.15.0'
    name: karvdash
    sources:
    - https://github.com/CARV-ICS-FORTH/karvdash
    type: application
    urls:
    - https://CARV-ICS-FORTH.github.io/karvdash/chart/karvdash-3.0.3.tgz
    version: 3.0.3
  - apiVersion: v2
    created: "2021-09-16T10:47:24.459346121Z"
    description: Karvdash provides a complete software stack for performing data science
      on Kubernetes
    digest: 102b9a8ac291f03392987a4c9fec241cca64b53c383cfe1382cdb05b33e8caa7
    kubeVersion: '>= 1.15.0'
    name: karvdash
    sources:
    - https://github.com/CARV-ICS-FORTH/karvdash
    type: application
    urls:
    - https://CARV-ICS-FORTH.github.io/karvdash/chart/karvdash-3.0.2.tgz
    version: 3.0.2
  - apiVersion: v2
    created: "2021-09-09T19:53:44.673565714Z"
    description: Karvdash provides a complete software stack for performing data science
      on Kubernetes
    digest: e509a294be8e31da4efc431ff1750457dcb4a50e2de520b36fc62e5a5c31bca0
    kubeVersion: '>= 1.15.0'
    name: karvdash
    sources:
    - https://github.com/CARV-ICS-FORTH/karvdash
    type: application
    urls:
    - https://CARV-ICS-FORTH.github.io/karvdash/chart/karvdash-3.0.1.tgz
    version: 3.0.1
  - apiVersion: v2
    created: "2021-09-03T08:26:47.931334469Z"
    description: Karvdash provides a complete software stack for performing data science
      on Kubernetes
    digest: bc79f38ff2f5b84e48d60621f5e60ba4cf9bdc7b2bf2ae7c68a9b6ea3390daea
    kubeVersion: '>= 1.15.0'
    name: karvdash
    sources:
    - https://github.com/CARV-ICS-FORTH/karvdash
    type: application
    urls:
    - https://CARV-ICS-FORTH.github.io/karvdash/chart/karvdash-3.0.0.tgz
    version: 3.0.0
  - apiVersion: v2
    created: "2021-06-28T11:15:37.32976498Z"
    description: Karvdash provides a complete software stack for performing data science
      on Kubernetes
    digest: 2d304b43b6c089ecbccceb9aa8c55d735bc789c99cb9b8f3ae1c31a9e1a2c24c
    kubeVersion: '>= 1.15.0'
    name: karvdash
    sources:
    - https://github.com/CARV-ICS-FORTH/karvdash
    type: application
    urls:
    - https://CARV-ICS-FORTH.github.io/karvdash/chart/karvdash-2.4.3.tgz
    version: 2.4.3
  - apiVersion: v2
    created: "2021-06-28T09:57:23.062385464Z"
    description: Karvdash provides a complete software stack for performing data science
      on Kubernetes
    digest: 63eb0d97fce968f54fee6924435e13a16b515dc0043dcef520ff7ff7860df8c3
    kubeVersion: '>= 1.15.0'
    name: karvdash
    sources:
    - https://github.com/CARV-ICS-FORTH/karvdash
    type: application
    urls:
    - https://CARV-ICS-FORTH.github.io/karvdash/chart/karvdash-2.4.2.tgz
    version: 2.4.2
  - apiVersion: v2
    created: "2021-06-18T08:03:44.022031009Z"
    description: Karvdash provides a complete software stack for performing data science
      on Kubernetes
    digest: efd07ddec32b261fa4ee10240875768797bb85823cb4f091f7ebd46c25578244
    kubeVersion: '>= 1.15.0'
    name: karvdash
    sources:
    - https://github.com/CARV-ICS-FORTH/karvdash
    type: application
    urls:
    - https://CARV-ICS-FORTH.github.io/karvdash/chart/karvdash-2.4.1.tgz
    version: 2.4.1
  - apiVersion: v2
    created: "2021-06-04T14:17:26.36993158Z"
    description: Karvdash provides a complete software stack for performing data science
      on Kubernetes
    digest: 5e6dfd758d66b1b015568a9bd53621acb68c83729aafc970d0da7125996958b9
    kubeVersion: '>= 1.15.0'
    name: karvdash
    sources:
    - https://github.com/CARV-ICS-FORTH/karvdash
    type: application
    urls:
    - https://CARV-ICS-FORTH.github.io/karvdash/chart/karvdash-2.3.1.tgz
    version: 2.3.1
  - apiVersion: v2
    created: "2021-05-13T16:16:58.697636707Z"
    description: Karvdash provides a complete software stack for performing data science
      on Kubernetes
    digest: 616367217c2f1528d09aa89f1cbe25a15866d62524cef51eda6c3013d15f0fcf
    kubeVersion: '>= 1.15.0'
    name: karvdash
    sources:
    - https://github.com/CARV-ICS-FORTH/karvdash
    type: application
    urls:
    - https://CARV-ICS-FORTH.github.io/karvdash/chart/karvdash-2.3.0.tgz
    version: 2.3.0
  - apiVersion: v2
    created: "2021-05-07T09:56:46.696463892Z"
    description: Karvdash provides a complete software stack for performing data science
      on Kubernetes
    digest: 917de6860d287d29b9bf19d29d6192c86406616db58571d68226bf50486cb35f
    kubeVersion: '>= 1.15.0'
    name: karvdash
    sources:
    - https://github.com/CARV-ICS-FORTH/karvdash
    type: application
    urls:
    - https://CARV-ICS-FORTH.github.io/karvdash/chart/karvdash-2.2.0.tgz
    version: 2.2.0
  - apiVersion: v2
    created: "2021-04-14T10:59:53.350750644Z"
    description: Karvdash provides a complete software stack for performing data science
      on Kubernetes
    digest: d4ee54dd71c5363f4b4749f2ce99f1ff68f31837a577c9862662f4a043b66b7b
    kubeVersion: '>= 1.15.0'
    name: karvdash
    sources:
    - https://github.com/CARV-ICS-FORTH/karvdash
    type: application
    urls:
    - https://CARV-ICS-FORTH.github.io/karvdash/chart/karvdash-2.1.0.tgz
    version: 2.1.0
  - apiVersion: v2
    created: "2021-03-23T11:18:20.107824221Z"
    description: Karvdash provides a complete software stack for performing data science
      on Kubernetes
    digest: 7af593b35b77b7f4ee7166712d351d61b07903dd91c867128e58ae7a359f3597
    kubeVersion: '>= 1.15.0'
    name: karvdash
    sources:
    - https://github.com/CARV-ICS-FORTH/karvdash
    type: application
    urls:
    - https://CARV-ICS-FORTH.github.io/karvdash/chart/karvdash-2.0.0.tgz
    version: 2.0.0
  knot:
  - apiVersion: v2
    created: "2022-11-21T09:36:11.119370485Z"
    description: Knot provides a complete environment for unleashing your productivity
      on Kubernetes
    digest: 4ea98197a56d3b78217571bce09f08cdb2d0e346b7e9b860818dd583ed85d08a
    kubeVersion: '>= 1.19.0'
    name: knot
    sources:
    - https://github.com/CARV-ICS-FORTH/knot
    type: application
    urls:
    - https://CARV-ICS-FORTH.github.io/knot/chart/knot-4.1.0.tgz
    version: 4.1.0
  - apiVersion: v2
    created: "2022-07-28T18:05:28.680824711Z"
    description: Knot provides a complete environment for unleashing your productivity
      on Kubernetes
    digest: 4949ed9a5eba3504e8bb21c551856a5eb7f9438363d125f4d18088d5ac1a96ca
    kubeVersion: '>= 1.19.0'
    name: knot
    sources:
    - https://github.com/CARV-ICS-FORTH/knot
    type: application
    urls:
    - https://CARV-ICS-FORTH.github.io/knot/chart/knot-4.0.1.tgz
    version: 4.0.1
  - apiVersion: v2
    created: "2022-07-19T14:31:53.367225582Z"
    description: Knot provides a complete environment for unleashing your productivity
      on Kubernetes
    digest: 52e800ebe8111de8089d1b047ddead5440155ba4227dea4ec6723b7e1cd56885
    kubeVersion: '>= 1.19.0'
    name: knot
    sources:
    - https://github.com/CARV-ICS-FORTH/knot
    type: application
    urls:
    - https://CARV-ICS-FORTH.github.io/knot/chart/knot-4.0.0.tgz
    version: 4.0.0
generated: "2022-11-21T09:36:11.117441808Z"
