site_name: Karvdash
site_url: https://carv-ics-forth.github.io/karvdash/docs
nav:
  - 'Overview': 'index.md'
  - 'Installation (bare metal)': 'install-bare-metal.md'
  - 'User guide': 'user-guide.md'
  - 'Technical notes': 'technical-notes.md'
theme:
  name: readthedocs
  logo: images/karvdash-blue.png
extra_css:
    - css/extra.css
repo_url: https://github.com/CARV-ICS-FORTH/karvdash
edit_uri: docs/docs
copyright: Â© 2020-2022, FORTH-ICS
