site_name: Knot
site_url: https://carv-ics-forth.github.io/knot/docs
nav:
  - 'Overview': 'index.md'
  - 'Deployment': 'deployment.md'
  - 'User guide': 'user-guide.md'
  - 'Technical notes': 'technical-notes.md'
use_directory_urls: false
theme:
  name: readthedocs
  logo: images/logo.png
extra_css:
  - css/extra.css
plugins:
  - include-markdown
repo_url: https://github.com/CARV-ICS-FORTH/knot
copyright: Â© 2020-2025, FORTH-ICS
