# Container image to use.
image:

# Include access-control rules for API and namespace discovery.
rbac:
  create: true

karvdash:
  # REQUIRED: If set, use this persistent volume claim for storing state (database, running services repository, template library).
  stateVolumeClaim:
  # REQUIRED: The host path to use for storing state, when no existing volume claim is set.
  stateHostPath:

  # The volume to store HTTP access and error logs.
  logsVolumeClaim:
  # The host path to use for storing logs, when no existing volume claim is set.
  logsHostPath:

  # Secret for Django. Use a random string of 50 characters (a default will be generated if empty).
  djangoSecret:
  # Set to anything to enable, empty to disable.
  djangoDebug:
  # The default admin password.
  adminPassword: admin
  # If set, the path to export the htpasswd file in.
  htpasswdExportDir:
  # The title of the dashboard.
  dashboardTitle: Dashboard
  # The theme of the dashboard.
  dashboardTheme: karvdash
  # If set, an option to "Report an issue" is shown in the user menu.
  issuesURL:
  # REQUIRED: The ingress URL used.
  ingressURL:
  # The URL of the container registry.
  registryURL:
  # The container registry certificate (use if self-signed).
  registryCert:
  # Set to anything to enable dataset management.
  datasetsAvailable:
  # REQUIRED: The base URL for the private and shared file domains.
  filesURL:
  # The size for the files persistent volume.
  filesSize: 1Pi
  # Other host paths to allow attaching to containers (separate with ":").
  allowedHostPathDirs:

  # List of service templates to disable on deployment (filenames).
  disabledServiceTemplates:
  # List of dataset templates to disable on deployment (identifiers).
  disabledDatasetTemplates:
  # List of predefined URL prefixes for services.
  serviceURLPrefixes:

  # Argo URL for integration with workflow frontend.
  argoURL:
  # Argo namespace for service account managment.
  argoNamespace:
