name: Publish to pages
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Publish to pages
    runs-on: ubuntu-latest
    container: python:3.7.9-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y make git
      - name: Build and install client
        run: |
          (cd client && python setup.py install)
      - name: Build and install docs
        run: |
          pip install -r docs/requirements.txt
          (cd docs && make html)
          mv docs/_build/html ./public
      - name: Copy over chart
        run: |
          cp -r chart ./public/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
